'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")>  _
    Partial Friend NotInheritable Class ChungJee
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As ChungJee = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New ChungJee()),ChungJee)
        
        Public Shared ReadOnly Property [Default]() As ChungJee
            Get
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://120.211.170.8:5000")>  _
        Public Property strNasHostName() As String
            Get
                Return CType(Me("strNasHostName"),String)
            End Get
            Set
                Me("strNasHostName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("zhanglj")>  _
        Public Property strNasUserName() As String
            Get
                Return CType(Me("strNasUserName"),String)
            End Get
            Set
                Me("strNasUserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strNasPassWord() As String
            Get
                Return CType(Me("strNasPassWord"),String)
            End Get
            Set
                Me("strNasPassWord") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("基础数据")>  _
        Public Property con_BASE_DATA() As String
            Get
                Return CType(Me("con_BASE_DATA"),String)
            End Get
            Set
                Me("con_BASE_DATA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property strNasSid() As String
            Get
                Return CType(Me("strNasSid"),String)
            End Get
            Set
                Me("strNasSid") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("单位信息表")>  _
        Public Property con_COMPANY_INFO() As String
            Get
                Return CType(Me("con_COMPANY_INFO"),String)
            End Get
            Set
                Me("con_COMPANY_INFO") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("/home/excelWeview2/")>  _
        Public Property con_NAS_HOME_FOLDERNAME() As String
            Get
                Return CType(Me("con_NAS_HOME_FOLDERNAME"),String)
            End Get
            Set
                Me("con_NAS_HOME_FOLDERNAME") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("开始日期：")>  _
        Public Property con_START_DATE() As String
            Get
                Return CType(Me("con_START_DATE"),String)
            End Get
            Set
                Me("con_START_DATE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("结束日期：")>  _
        Public Property con_END_DATE() As String
            Get
                Return CType(Me("con_END_DATE"),String)
            End Get
            Set
                Me("con_END_DATE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("数据聚合")>  _
        Public Property strTabName() As String
            Get
                Return CType(Me("strTabName"),String)
            End Get
            Set
                Me("strTabName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("{""data"":[{""url"":""https://e.dianping.com/couponrecord/queryCouponRecordDetails"",""o"& _ 
            "ldValue"":"":20"",""newValue"":"":300""},{""url"":""https://e.dianping.com/couponrecord/co"& _ 
            "nsumeItemsNewDownload""},{""url"":""https://e.dianping.com/smartBill/download/downlo"& _ 
            "adLink""},{""url"":""https://e.dianping.com/gateway/adviser/data?componentId=flowTab"& _ 
            "leDownloadPCAsync&pageType=flowAnalysis""},{""url"":""/s"",""enable"":""false""},{""url"":"""& _ 
            "https://mss-shon.sankuai.com/merchant-adviser-process/""},{""url"":""https://mss-sho"& _ 
            "n.sankuai.com/settle/382206_%E6%89%93%E6%AC%BE%E8%AE%B0%E5%BD%95""},{""url"":""https"& _ 
            "://mss-shon.sankuai.com/settle/382206_%E5%9B%A2%E8%B4%AD%E6%89%93%E6%AC%BE%E8%AE"& _ 
            "%B0%E5%BD%95""},{""url"":""https://mss-shon.sankuai.com/settle/382206_团购收益明细""},{""url"& _ 
            """:""https://mss-shon.sankuai.com/settle/382206_%E5%9B%A2%E8%B4%AD%E5%B7%B2%E7%BB%"& _ 
            "93%E7%AE%97%E8%B4%A6%E5%8D%95%E6%98%8E%E7%BB%86""}]}")>  _
        Public Property jsonUrlList() As String
            Get
                Return CType(Me("jsonUrlList"),String)
            End Get
            Set
                Me("jsonUrlList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://e.dianping.com/")>  _
        Public Property strHomePage() As String
            Get
                Return CType(Me("strHomePage"),String)
            End Get
            Set
                Me("strHomePage") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("{""data"":[{""url"":""https://e.dianping.com/app/np-mer-voucher-web-static/records"",""l"& _ 
            "bPage"":""document.getElementsByTagName('iframe')[0].contentDocument.getElementsBy"& _ 
            "ClassName('ant-pagination-total-text')[0].innerText"",""tooltxtForward"":""if (docum"& _ 
            "ent.querySelector('iframe').contentDocument.getElementsByClassName(' ant-paginat"& _ 
            "ion-prev')[0].className==' ant-pagination-prev'){document.querySelector('iframe'"& _ 
            ").contentDocument.getElementsByClassName(' ant-pagination-prev')[0].click();true"& _ 
            "}else{false}"",""tooltxtBackward"":""if (document.querySelector('iframe').contentDoc"& _ 
            "ument.getElementsByClassName(' ant-pagination-next')[0].className==' ant-paginat"& _ 
            "ion-next'){document.querySelector('iframe').contentDocument.getElementsByClassNa"& _ 
            "me(' ant-pagination-next')[0].click();true}else{false}""},{""url"":""https://e.dianp"& _ 
            "ing.com/couponrecord/queryCouponRecordDetails/dsfsd"",""lbPage"":""document.getEleme"& _ 
            "ntsByTagName('iframe')[0].contentDocument.getElementsByClassName('ant-pagination"& _ 
            "-total-text')[0].innerText"",""btnForward"":""document.getElementsByTagName('iframe'"& _ 
            ")[0].contentDocument.getElementsByClassName('anticon anticon-left')[1].click()"","& _ 
            """btnBackward"":""document.getElementsByTagName('iframe')[0].contentDocument.getEle"& _ 
            "mentsByClassName('anticon anticon-right')[1].click()""}]}")>  _
        Public Property jsonBottomButtonScript() As String
            Get
                Return CType(Me("jsonBottomButtonScript"),String)
            End Get
            Set
                Me("jsonBottomButtonScript") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Sub strVBAFunctionName(strFileName As String)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Application.ScreenUpdating = False"& _ 
            ": Application.EnableEvents = False"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Dim strRangeAddress As String, strListObject"& _ 
            "Name As String, wbDownload As Workbook, shDownload As Worksheet, shCurrent As Wo"& _ 
            "rksheet, xlApp As Application"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Dim rowItem As Range, intOffsetRow As Integer: in"& _ 
            "tOffsetRow = 0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Set xlApp = New Application: Set wbDownload = xlApp.Workbooks.Op"& _ 
            "en(strFileName): Set shDownload = wbDownload.Sheets(1)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"intOffsetRow = shDownloa"& _ 
            "d.UsedRange.Columns(shDownload.UsedRange.Columns.Count).Cells(1, 1).End(Excel.xl"& _ 
            "Down).Row"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"If intOffsetRow = shDownload.UsedRange.Rows.Count Then intOffsetRow ="& _ 
            " 0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Dim regEx As Object:  Set regEx = CreateObject(""VBScript.RegExp""): regEx.Glo"& _ 
            "bal = True: regEx.Pattern = ""[\u4e00-\u9fa5]+"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"strListObjectName = regEx.Replac"& _ 
            "e(strFileName, """"): If strListObjectName = """" Then strListObjectName = ""TEMP"""&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"s"& _ 
            "trRangeAddress = shDownload.UsedRange.Offset(intOffsetRow).Resize(shDownload.Use"& _ 
            "dRange.Rows.Count - intOffsetRow).Address"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Set shCurrent = ThisWorkbook.ActiveSh"& _ 
            "eet: shCurrent.Cells.Clear"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"shCurrent.Range(shDownload.UsedRange.Address).Value "& _ 
            "= shDownload.UsedRange.Value"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"wbDownload.Close SaveChanges:=False: Kill strFileN"& _ 
            "ame: xlApp.Quit: Set xlApp = Nothing: Set wbDownload = Nothing: Set shDownload ="& _ 
            " Nothing"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"On Error Resume Next: shCurrent.AutoFilterMode = False"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"With shCurrent"& _ 
            ".ListObjects.Add(xlSrcRange, shCurrent.Range(strRangeAddress), , xlYes)"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"    .Na"& _ 
            "me = strListObjectName: .DataBodyRange.Font.Size = 9: .DataBodyRange.HorizontalA"& _ 
            "lignment = xlCenter: .HeaderRowRange.HorizontalAlignment = xlCenter: .ShowAutoFi"& _ 
            "lterDropDown = False"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"End With"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"Application.ScreenUpdating = True: Application.E"& _ 
            "nableEvents = True"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"End Sub")>  _
        Public Property strNoVBAFunction() As String
            Get
                Return CType(Me("strNoVBAFunction"),String)
            End Get
            Set
                Me("strNoVBAFunction") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property jsonRequestFilter() As String
            Get
                Return CType(Me("jsonRequestFilter"),String)
            End Get
            Set
                Me("jsonRequestFilter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("public sub frmShow()"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"If frmLoading_ChungJee.Visible = False Then frmLoading_Chun"& _ 
            "gJee.Show 0"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"end sub"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"public sub frmHidden()"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"If frmLoading_ChungJee.Visible = T"& _ 
            "rue Then frmLoading_ChungJee.Hide"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"end sub")>  _
        Public Property strLoadFormFunction() As String
            Get
                Return CType(Me("strLoadFormFunction"),String)
            End Get
            Set
                Me("strLoadFormFunction") = value
            End Set
        End Property
    End Class
End Namespace
